minor/feature/UBI-526-fuzzing
Ubivius/microservice-template pull request #69
Opened 2021-10-29 17:52 UTC by JeremiSavard

#### What changes does this PR contain?
fuzzing for json marshal/unmarshal
#### Which JIRA ticket ID's are associated with this PR?
ubi-526
#### Additional comments and information

2021-10-29 21:08 UTC, ArcticWalrus requested changes

2021-10-29 21:08 UTC, ArcticWalrus commented on pkg/fuzzing/fuzz.go
> +func Fuzz(data []byte) int {
Can you add some documentation in a readme or something in this directory on how to use the package

Like running the go-fuzz command or at least have a link to the package somewhere

2021-11-01 23:44 UTC, ysma500 approved these changes
Other than comments, LGTM

2021-11-01 23:44 UTC, ysma500 commented on pkg/fuzzing/corpus/1d9de5f154bbfe8edadbd5b13d4ffd487c2b7448-2
> +{"":"","":7,"":""}
No return EOF

2021-11-01 23:44 UTC, ysma500 commented on pkg/fuzzing/corpus/86f9d6aef7b74718b27f824cb4f855e43273da4d-1
> +{"Name":"Jeremi","Price":7,"SKU":"abs289102309bs-abscd"}
Same here: No return EOF

2021-11-01 23:44 UTC, ysma500 commented on pkg/fuzzing/corpus/acee34f457cebfeb0a2a4082b804812befb64015-1
> +{"e":"","ce":7,"SKU":""}
Same here: No return EOF

2021-11-01 23:44 UTC, ysma500 commented on pkg/fuzzing/corpus/d1bc3451814111f1b15bf3254eed284d1c98323d-1
> +{"Name":"Jeremi","Price":7,"SKU":"abs-abs-ªabscd"}
Same here: No return EOF

2021-11-02 16:22 UTC, ArcticWalrus approved these changes

2021-11-03 00:46 UTC, merged