major/feature/UBI-542-addAuthMiddleware
Ubivius/microservice-template pull request #71
Opened 2021-11-04 19:44 UTC by JeremiSavard

#### What changes does this PR contain?
add middleware to validate token
#### Which JIRA ticket ID's are associated with this PR?
ubi-542
#### Additional comments and information

2021-11-14 15:21 UTC, ysma500 requested changes

2021-11-14 15:21 UTC, ysma500 commented on chart/Chart.yaml
> +appVersion: 0.0.0-rc
This shouldn't be a commited change

2021-11-14 15:21 UTC, ysma500 commented on chart/values.yaml
> +  tag: 0.0.0-rc
Same here

2021-11-15 13:48 UTC, ArcticWalrus requested changes

2021-11-15 13:48 UTC, ArcticWalrus commented on go.mod
> +	github.com/Ubivius/shared-authentication v0.0.0-20211113221950-120d47cecb60 // indirect
Should do a git tag for v1.0.0 or something in repo and import the exact version

2021-11-15 13:48 UTC, ArcticWalrus commented on pkg/router/router.go
> +	healthRouter := router.Methods(http.MethodGet).Subrouter()
Do you know if setting another http.Method get router stop the other get endpoints from being exposed

2021-11-16 02:10 UTC, ysma500 approved these changes
LGTM

2021-11-18 00:04 UTC, ArcticWalrus approved these changes

2021-11-18 01:53 UTC, merged